# Generated by Django 5.0.6 on 2024-07-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='static/dishes/'),
        ),
    ]
