# Generated by Django 5.0.6 on 2024-07-20 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_squashed_0005_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='date_last_made',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='static/dishes/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
