# Generated by Django 5.1.5 on 2025-01-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("ingredients", models.JSONField()),
                ("tags", models.JSONField()),
            ],
        ),
    ]
