# Generated by Django 5.1.5 on 2025-01-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dishes", "0003_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.JSONField(default=list, null=True),
        ),
    ]
